package org.opentestsystem.ap.timstool.exception;


/**
 * Throw this when there is an error during the execution of a command.  The idea is to wrap whatever exception is
 * caught then throw CommandException up the chain where it is handled at a central point.
 */
public class CommandException extends RuntimeException {

    public CommandException(String message) {
        super(message);
    }
}
